name: Run Jest

on:
  pull_request:
    branches:
      - testingTwo
    tags:
      - v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: stefanoeb/jest-action@1.0.0
