name: Run Jest

on:
  push:
    branches:
      - testing
    tags:
      - v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/hello-world-action
    - uses: stefanoeb/jest-action@1.0.0
