name: Run Tests

on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        cd brain-tag
        npm ci
        npm run build --if-present
        npm test
        cd ../
      env:
        CI: true