name: Run Tests

on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install and test
      run: |
        cd brain-tag
        npm ci
        npm test
        cd ../
      env:
        CI: true